### ISSUE TITLE
first result is showing undefined

### ISSUE THREAD

**Issue by gabepettus** [carinalullman/Group-Project#37]
both the first restaurant and the first trail are undefined. why?

**Comment by BenHCalvert** [comment]
I was going to take a stab at this today but couldn't replicate the issue. Are you all still seeing this?

**Comment by gabepettus** [comment]
I have not seen this tonight, so far. If so I will be sure to capture details. 
Otherwise I recommend we wait until Thursday, see if we ca reproduce it. If not then we can close it non-reproducible.
