### ISSUE TITLE
create getTrails function

### ISSUE THREAD

**Issue by gabepettus** [carinalullman/Group-Project#5]
Create javascript function to get trails information'

inputs: starting Location, distance to train
output: array of objects (trail information)

call hikingProjectApi passing to it id, lat,lon and distance to trail, and number of trails (20)
call getDistance for each trail and current location
add distance from cur location to each trail to array
return arr of trail object

**Comment by carinalullman** [comment]
this function was already written, I just added the .distance property to the trails objects that the API returned.
